server:
  port: 8090
  servlet:
    context-path: /kafkaPrivoder
spring:
  kafka:
    bootstrap-servers: 192.168.27.25:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3  #  重试次数
kafka:
  topic:
    topic4UserNotice: topic4UserNotice
    topic4Test: topic4Test
